name: 'Metaphor DBT Metadata'
description: 'Publish DBT metadata to Metaphor'
inputs:
  manifest:
    description: 'Path to DBT manifest.json file'
    required: true

  catalog:
    description: 'Path to DBT catalog.json file'
    required: true

  account:
    description: 'The database service account this DBT project is connected to'
    required: true

  project-source-url:
    description: 'The source code URL pointing to the project root directory'
    required: false
    default: ''

  docs-base-url:
    description: 'The base URL serving the dbt generated docs'
    required: false
    default: ''

  s3-path: 
    description: 'S3 path for outputting the metadata'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.manifest }}
    - ${{ inputs.catalog }}
    - ${{ inputs.account }}
    - ${{ inputs.project-source-url }}
    - ${{ inputs.docs-base-url }}
    - ${{ inputs.s3-path }}
